---
- name: Query Trivia API
  hosts: localhost
  gather_facts: no
  vars_prompt:
    - name: "AMOUNT"
      prompt: "Enter the amount of questions"
      default: "2"
      private: no
    - name: "DIFFICULTY"
      prompt: "Enter the difficulty (easy, medium, hard)"
      default: "easy"
      private: no

  tasks:
    - name: Call custom API module
      trivia_api:
        amount: "{{ AMOUNT }}"
        difficulty: "{{ DIFFICULTY }}"
      register: api_result

    - name: Write result to json file
      copy:
        dest: api_result.json
        content: "{{ api_result | to_json }}"

    - name: Display API response
      debug:
        msg: "{{ item['question'] }} Answer: {{ item['correct_answer'] }}"
      loop: "{{ api_result.questions }}"

